name: file_server_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  rxdart:
  provider: ^4.0.5
  shared_preferences: ^0.5.6+3
  flutter_form_bloc: ^0.12.2
  form_bloc:
  jwt_decode: ^0.1.0
  equatable: ^1.1.1
  loading_overlay: ^0.2.1
  responsive_scaffold: ^1.3.0+2



  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
